name       : libslirp
version    : 4.7.0
release    : 7
source     :
    - git|https://gitlab.freedesktop.org/slirp/libslirp.git : v4.7.0
license    : GPL-2.0-or-later
component  : virt
summary    : User-mode networking for unprivileged network namespaces
description: |
    A general purpose TCP-IP emulator used by virtual machine hypervisors to provide virtual networking services.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
